### PR TITLE
persistent spike lines and axis labelling on multi-plots

### PR DESCRIPTION
**Pull request by slawlor**
This PR supports adding persistent spike lines on click on charts. This way, in multi-plot charts, you can see the pinned spike line across all charts as you drag & zoom in other charts.

Additionally we added missing sub-labels on multi plots so the xaxis labels can be replicated on each subsequent plot if wished.

Apologies, but I cannot identify the maintainers except for @archmoj. If you would prefer other reviewers please let me know or link them to the PR. This is related to issue #4052 in plotly/plotly.js and #2539 as well

### CODE REVIEW

**Comment by slawlor** [comment]
Also tagging @etpinard as a potential reviewer

**Comment by Glopter** [comment]
@slawlor This would be a great feature. Why did you close this PR?

**Comment by slawlor** [comment]
Because it had been 3 years with no activity lol. I was cleaning up my GitHub account is all

**Comment by Glopter** [comment]
Fair enough. It's a shame that the mills here grind so slowly. I would have loved to see this feature in production.

**Comment by slawlor** [comment]
> Fair enough. It's a shame that the mills here grind so slowly. I would have loved to see this feature in production.

If you have better luck with the plotly maintainers, please feel free to comandeer the changeset and try and get them to review it! Would love to see it merged eventually, but I don't have great hope unfortunately.

**Pull request closed without merging**
